languageCode = "ja-JP"
title = "呉さんの諸々"
baseURL = "http://wuzhonglin.link/"
contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
buildDrafts = false
canonifyURLs = true
hasCJKLanguage = true
themesDir = "themes"
staticDir = "static"
theme = "robust"
uglyurls = false
relativeURLs = true

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "呉さんの諸々を記述したもの"
  author = "wu zhonglin"

[outputs]
  page = [ "HTML", "AMP" ]
